apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaexpress5-deployment
  namespace: uat
  labels:
    app: javaexpress5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaexpress5
  template:
    metadata:
      labels:
        app: javaexpress5
    spec:
      containers:
      - name: javaexpress5
        image: andrei4455/springjavaexpress-docker-demo:springjavaexpress-docker-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
         tcpSocket:
           port: 8080
         initialDelaySeconds: 5
         periodSeconds: 10
        livenessProbe:
         tcpSocket:
           port: 8080
         initialDelaySeconds: 15
         periodSeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: javaexpress5-service
spec:
  type: NodePort
  selector:
    app: javaexpress5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32320
